import PDFDocument from "pdfkit"
import type { LungifyReport } from "@/lib/report-types"

type HospitalProfile = {
  name: string
  department: string
  address: string
  phone: string
  email: string
}

function defaultHospitalProfile(): HospitalProfile {
  return {
    name: process.env.HOSPITAL_NAME || "Lungify General Hospital",
    department: process.env.HOSPITAL_DEPARTMENT || "Department of Radiology and Thoracic Imaging",
    address: process.env.HOSPITAL_ADDRESS || "221 Medical District, Health City",
    phone: process.env.HOSPITAL_PHONE || "+1 (555) 120-2026",
    email: process.env.HOSPITAL_EMAIL || "radiology@lungify-hospital.org",
  }
}

function pdfToBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []

    doc.on("data", (chunk) => {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk))
    })
    doc.on("end", () => resolve(Buffer.concat(chunks)))
    doc.on("error", reject)
    doc.end()
  })
}

function sectionTitle(doc: PDFKit.PDFDocument, title: string) {
  doc.moveDown(0.7)
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#0f172a").text(title)
  doc.moveDown(0.3)
}

function keyValueRow(doc: PDFKit.PDFDocument, key: string, value: string) {
  doc.font("Helvetica-Bold").fontSize(10).fillColor("#1e293b").text(`${key}: `, {
    continued: true,
  })
  doc.font("Helvetica").fontSize(10).fillColor("#334155").text(value)
}

export async function buildHospitalReportPdf(report: LungifyReport) {
  const profile = defaultHospitalProfile()
  const doc = new PDFDocument({
    size: "A4",
    margin: 48,
    info: {
      Title: `Lungify Hospital Report - ${report.id}`,
      Author: report.radiologistUserId,
      Subject: "Lung cancer detection and analysis report",
      Keywords: "lung cancer, ct scan, radiology, report",
      Creator: "Lungify AI",
    },
  })

  doc.rect(0, 0, 612, 110).fill("#0b1324")
  doc.fillColor("white")
  doc.font("Helvetica-Bold").fontSize(22).text(profile.name, 48, 34)
  doc.font("Helvetica").fontSize(10).fillColor("#cbd5e1").text(profile.department, 48, 62)
  doc.text(`${profile.address} | ${profile.phone} | ${profile.email}`, 48, 78)

  doc.fillColor("#0f172a")
  doc.moveDown(5.2)
  doc.font("Helvetica-Bold").fontSize(16).text("Professional Radiology Report")
  doc.moveDown(0.2)
  doc.font("Helvetica").fontSize(10).fillColor("#475569").text("Prepared for clinical review and patient communication")

  sectionTitle(doc, "Patient and Case Details")
  keyValueRow(doc, "Report ID", report.id)
  keyValueRow(doc, "Patient Name", report.patientName)
  keyValueRow(doc, "Patient Identifier", report.patientUserId)
  keyValueRow(doc, "Radiologist", report.radiologistUserId)
  keyValueRow(doc, "CT Scan Reference", report.scanReference)
  keyValueRow(doc, "Report Status", report.status.toUpperCase())
  keyValueRow(doc, "Generated On", new Date(report.updatedAt).toLocaleString())

  sectionTitle(doc, "AI Prediction Summary")
  keyValueRow(doc, "Prediction", report.prediction.label)
  keyValueRow(doc, "Confidence", `${Math.round(report.prediction.confidence * 100)}%`)
  keyValueRow(doc, "Model Version", report.prediction.modelVersion)
  keyValueRow(doc, "Risk Score", report.prediction.score.toFixed(4))

  sectionTitle(doc, "Radiologist Findings")
  doc.font("Helvetica").fontSize(10).fillColor("#334155").text(report.findings, {
    lineGap: 2,
  })

  sectionTitle(doc, "Clinical Advice and Follow-Up")
  report.advice.forEach((item, idx) => {
    doc.font("Helvetica-Bold").fontSize(10).fillColor("#0f172a").text(`${idx + 1}. `, {
      continued: true,
    })
    doc.font("Helvetica").fontSize(10).fillColor("#334155").text(item)
  })

  sectionTitle(doc, "Compliance and Disclaimer")
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor("#64748b")
    .text(
      "This report is generated through a clinical workflow that includes AI-assisted decision support and licensed radiologist review. The final diagnosis must always be interpreted with full clinical history, prior imaging, and physician judgment.",
      { lineGap: 2 },
    )

  doc.moveDown(1.4)
  doc.font("Helvetica").fontSize(10).fillColor("#0f172a").text("Radiologist Signature: ____________________________")
  doc.moveDown(0.6)
  doc.font("Helvetica").fontSize(10).fillColor("#0f172a").text("Patient Acknowledgement: _________________________")

  doc.moveDown(1.5)
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#94a3b8")
    .text(`Document generated by Lungify AI platform on ${new Date().toISOString()}.`, {
      align: "center",
    })

  return pdfToBuffer(doc)
}
